version: '3.8'

services:
  ticket-checker:
    build: .
    container_name: sportstiming-checker
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Copenhagen # Set to your timezone
    restart: unless-stopped
    command: [ "python", "ticket_checker.py", "--config", "config.json", "--notify-all", "--interval", "300" ]

    # Uncomment for testing
    # command: ["python", "ticket_checker.py", "--test-telegram", "--config", "config.json"]

    # Health check
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('https://httpbin.org/status/200', timeout=5)" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
